Fri, 23 Oct 2020 08:54:39-run_all_case.py-test_businessInfoReg.py-[line:38]-INFO-[日志信息]: 开始执行脚本test_businessInforReg:

[08:54:43][DEBUG]<airtest.core.android.adb> C:\Users\shaojunshuai\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 18f0acb7 shell am force-stop com.netease.open.pocoservice
Exception in thread Thread-31:
Traceback (most recent call last):
  File "C:\Users\shaojunshuai\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\shaojunshuai\AppData\Local\Programs\Python\Python36\lib\site-packages\poco\drivers\android\uiautomation.py", line 124, in run
    self.poco._start_instrument(self.port_to_ping)  # 尝试重启
  File "C:\Users\shaojunshuai\AppData\Local\Programs\Python\Python36\lib\site-packages\poco\drivers\android\uiautomation.py", line 247, in _start_instrument
    self.adb_client.shell(['am', 'force-stop', PocoServicePackage])
  File "C:\Users\shaojunshuai\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\android\adb.py", line 371, in shell
    out = self.raw_shell(cmd)
  File "C:\Users\shaojunshuai\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\android\adb.py", line 329, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "C:\Users\shaojunshuai\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\android\adb.py", line 192, in cmd
    raise DeviceConnectionError(stderr)
airtest.core.error.DeviceConnectionError: b"error: device '18f0acb7' not found\r\n"

Fri, 23 Oct 2020 08:54:50-test_businessInforReg-Assert.py-[line:124]-INFO-[日志信息]: except_result = actul_result, except_result is 企业基本资料, actul_result is 企业基本资料
Fri, 23 Oct 2020 08:54:50-run_all_case.py-test_businessInfoReg.py-[line:49]-INFO-[日志信息]: 企业基本资料画面正常显示
