{
  "uid" : "f4aa87fc90ef7b3f",
  "name" : "test_config_common",
  "fullName" : "test_case.test_Api_demo.test_demo#test_config_common",
  "historyId" : "12451970f50aab0ec4d353f609012c2f",
  "time" : {
    "start" : 1600412876536,
    "stop" : 1600412876540,
    "duration" : 4
  },
  "description" : "测试http://calapi.51jirili.com/config/common接口",
  "descriptionHtml" : "<p>测试http://calapi.51jirili.com/config/common接口</p>\n",
  "status" : "broken",
  "statusMessage" : "NameError: name 'opera_url' is not defined",
  "statusTrace" : "@pytest.mark.run(order=1)\n    @allure.severity(\"blocker\")\n    @allure.description(\"测试http://calapi.51jirili.com/config/common接口\")\n    @allure.testcase(\"http://calapi.51jirili.com/config/common\", \"测试用例地址 \uD83D\uDC47\")\n    def test_config_common():\n        def_name = sys._getframe().f_code.co_name\n        test_Assert = Assert.Assertions(def_name)\n        logger.info(\"开始执行脚本%s:\\n\", def_name)\n        # opera_url = server_ip('realse') + yamldict['test_operation_list']['url']\n>       opera_result = RequestsHandler().post_Req(url=opera_url, params='')\nE       NameError: name 'opera_url' is not defined\n\ntest_case\\test_Api_demo\\test_demo.py:32: NameError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "description" : "测试http://calapi.51jirili.com/config/common接口",
    "status" : "broken",
    "statusMessage" : "NameError: name 'opera_url' is not defined",
    "statusTrace" : "@pytest.mark.run(order=1)\n    @allure.severity(\"blocker\")\n    @allure.description(\"测试http://calapi.51jirili.com/config/common接口\")\n    @allure.testcase(\"http://calapi.51jirili.com/config/common\", \"测试用例地址 \uD83D\uDC47\")\n    def test_config_common():\n        def_name = sys._getframe().f_code.co_name\n        test_Assert = Assert.Assertions(def_name)\n        logger.info(\"开始执行脚本%s:\\n\", def_name)\n        # opera_url = server_ip('realse') + yamldict['test_operation_list']['url']\n>       opera_result = RequestsHandler().post_Req(url=opera_url, params='')\nE       NameError: name 'opera_url' is not defined\n\ntest_case\\test_Api_demo\\test_demo.py:32: NameError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "ee0cde03e1db0053",
      "name" : "log",
      "source" : "ee0cde03e1db0053.txt",
      "type" : "text/plain",
      "size" : 78
    }, {
      "uid" : "57d744b3eed57b98",
      "name" : "stderr",
      "source" : "57d744b3eed57b98.txt",
      "type" : "text/plain",
      "size" : 125
    } ],
    "parameters" : [ ],
    "hasContent" : true,
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "blocker"
  }, {
    "name" : "tag",
    "value" : "run(order=1)"
  }, {
    "name" : "parentSuite",
    "value" : "test_case.test_Api_demo"
  }, {
    "name" : "suite",
    "value" : "test_demo"
  }, {
    "name" : "host",
    "value" : "A02-03-00033"
  }, {
    "name" : "thread",
    "value" : "24404-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_case.test_Api_demo.test_demo"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ {
    "name" : "测试用例地址 \uD83D\uDC47",
    "url" : "http://calapi.51jirili.com/config/common",
    "type" : "test_case"
  } ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "blocker",
    "retries" : [ {
      "uid" : "6a7a2fbc717ff0d6",
      "status" : "broken",
      "statusDetails" : "NameError: name 'opera_url' is not defined",
      "time" : {
        "start" : 1600412752759,
        "stop" : 1600412752762,
        "duration" : 3
      }
    }, {
      "uid" : "185738286dd7486a",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='calapi.51jirili.comhttp', port=80): Max retries exceeded with url: //calapi.51jirili.com/config/common (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B4DCAE6D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "time" : {
        "start" : 1600411387255,
        "stop" : 1600411387489,
        "duration" : 234
      }
    }, {
      "uid" : "9b3efd460df57b82",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='calapi.51jirili.comhttp', port=80): Max retries exceeded with url: //calapi.51jirili.com/config/common (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D8CFBA3F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "time" : {
        "start" : 1600333992756,
        "stop" : 1600333992800,
        "duration" : 44
      }
    }, {
      "uid" : "38dc692904a05c4a",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='calapi.51jirili.comhttp', port=80): Max retries exceeded with url: //calapi.51jirili.com/config/common (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B1A6976E80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "time" : {
        "start" : 1600304444079,
        "stop" : 1600304444094,
        "duration" : 15
      }
    }, {
      "uid" : "4c3ea0487a33ad52",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='calapi.51jirili.comhttp', port=80): Max retries exceeded with url: //calapi.51jirili.com/config/common (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002171A4D6CD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "time" : {
        "start" : 1600304131668,
        "stop" : 1600304131699,
        "duration" : 31
      }
    }, {
      "uid" : "93fe6598bb1271cd",
      "status" : "broken",
      "statusDetails" : "AttributeError: type object 'Log' has no attribute 'info'",
      "time" : {
        "start" : 1600304088275,
        "stop" : 1600304088290,
        "duration" : 15
      }
    }, {
      "uid" : "39fa6d395a599b39",
      "status" : "broken",
      "statusDetails" : "NameError: name 'logger' is not defined",
      "time" : {
        "start" : 1600303855940,
        "stop" : 1600303855940,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "run(order=1)" ]
  },
  "source" : "f4aa87fc90ef7b3f.json",
  "parameterValues" : [ ]
}