{"name": "test_companyRegister", "status": "broken", "statusDetails": {"message": "redis.exceptions.ResponseError: Command # 11 (GET path:plan:query:customer0kf54s1dr-0174-7495ff0a-8a8a0000-0037) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value", "trace": "@pytest.mark.run(order=1)\n    @allure.severity(\"blocker\")\n    @allure.description(\"ÊµãËØï http://10.10.128.152:10053/user/register ‰∏≠Â∞èÂæÆ‰ºÅ‰∏öÊ≥®ÂÜåÊµÅÁ®ã\")\n    @allure.testcase(\"http://10.10.128.152:10053/user/register\", \"Ê≥®ÂÜå üëá\")\n    def test_companyRegister():\n        if runMode == 'UI':\n            def_name = sys._getframe().f_code.co_name\n            test_Assert = Assert.Assertions(def_name)\n            logger.info(\"ÂºÄÂßãÊâßË°åËÑöÊú¨%s:\\n\", def_name)\n    \n            driver = webdriver.Chrome()\n            driver.maximize_window()\n            driver.get(url_ui_register)\n            # db‰∏≠Ê∏ÖÈô§Â∑≤Ê≥®ÂÜåÁöÑË¥¶Êà∑\n            deleteInforMobile()\n            logger.info(\"ÂØπÂ∑≤Ê≥®ÂÜåÁöÑË¥¶Êà∑ËøõË°åÂà†Èô§Êìç‰Ωú\")\n            sleep(1)\n            waitUntilClick(driver, loginOn.btn_agree_css.value)\n            driver.find_element_by_css_selector(loginOn.btn_agree_css.value).click()\n    \n            waitUntilDisplay(driver, loginOn.input_act_css.value)\n            driver.find_element_by_css_selector(loginOn.input_act_css.value).send_keys(act)\n            driver.find_element_by_css_selector(loginOn.input_pwd_css.value).send_keys(pwd)\n            driver.find_element_by_css_selector(loginOn.input_conPwd_css.value).send_keys(pwd)\n            waitUntilClick(driver, loginOn.btn_phoneCode_css.value)\n            sleep(2)\n            flushDb()\n            driver.find_element_by_css_selector(loginOn.btn_phoneCode_css.value).click()\n    \n            while 1:\n>               message = getPhoneMessage().get(\"regMes\")\n\ntest_flow\\test_Authentication\\test_login.py:77: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\dbLink.py:192: in getPhoneMessage\n    for (k, v) in zip(key_list, pipe.execute()):\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\redis\\client.py:4019: in execute\n    return execute(conn, stack, raise_on_error)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\redis\\client.py:3934: in _execute_transaction\n    self.raise_first_error(commands, response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = Pipeline<ConnectionPool<Connection<host=10.10.128.128,port=6739,db=3>>>\ncommands = [(('GET', b'order:track:0kf52p6z4-0174-749455fd-8a8a0000-0014'), {}), (('GET', b'ct:count:guarantee0kfcfg8zr-0174-748b...'token:f2bafde3-a845-4aab-a02d-ba2102fc0545'), {}), (('GET', b'ct:count:debt0kfewvl7d-n0llsm-o9erlk-00002d'), {}), ...]\nresponse = [b'284566946:3220', b'3', b'284566946:3180', b'284566946:3320', b'{\"@class\":\"com.bird.web.sso.ticket.ServerTicket\",\"us...\",1602480305033],\"expireTime\":[\"java.util.Date\",1602501905033],\"appClaims\":{\"@class\":\"java.util.HashMap\"}}', b'0', ...]\n\n    def raise_first_error(self, commands, response):\n        for i, r in enumerate(response):\n            if isinstance(r, ResponseError):\n                self.annotate_exception(r, i + 1, commands[i][0])\n>               raise r\nE               redis.exceptions.ResponseError: Command # 11 (GET path:plan:query:customer0kf54s1dr-0174-7495ff0a-8a8a0000-0037) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\redis\\client.py:3968: ResponseError"}, "description": "ÊµãËØï http://10.10.128.152:10053/user/register ‰∏≠Â∞èÂæÆ‰ºÅ‰∏öÊ≥®ÂÜåÊµÅÁ®ã", "attachments": [{"name": "log", "source": "8b6a99cc-724b-462d-b742-f96dd127e3ad-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c25f6120-aa66-49fc-aebc-6aff00755f2b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "86192797-5154-45e7-bda6-bd1a25cebe19-attachment.txt", "type": "text/plain"}], "start": 1602480683449, "stop": 1602480697397, "uuid": "2d8bfd56-7a84-4cc4-b075-5114ae23a03e", "historyId": "dd0646a5c1a798e47c4f25747509dea9", "testCaseId": "1fe2bac8daa9cfa6b5ae5069ce9a9205", "fullName": "test_flow.test_Authentication.test_login#test_companyRegister", "labels": [{"name": "severity", "value": "blocker"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "test_flow.test_Authentication"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "A02-03-00033"}, {"name": "thread", "value": "11416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_flow.test_Authentication.test_login"}], "links": [{"type": "test_case", "url": "http://10.10.128.152:10053/user/register", "name": "Ê≥®ÂÜå üëá"}]}