{"name": "test_infoReg", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (1242, 'Subquery returns more than 1 row')", "trace": "@pytest.mark.run(order=2)\n    @allure.severity(\"blocker\")\n    @allure.description(\"ÊµãËØï http://10.10.128.152:10053/personal/set/certification ‰∏™‰∫∫ÂÆûÂêçËÆ§ËØÅ\")\n    @allure.testcase(\"http://10.10.128.152:10053/personal/set/certification\", \"‰∏™‰∫∫ÂÆûÂêçËÆ§ËØÅ üëá\")\n    def test_infoReg():\n        def_name = sys._getframe().f_code.co_name\n        test_Assert = Assert.Assertions(def_name)\n        logger.info(\"ÂºÄÂßãÊâßË°åËÑöÊú¨%s:\\n\", def_name)\n    \n        # ÂØπ‰∏™‰∫∫‰ø°ÊÅØ‰ºÅ‰∏ö‰ø°ÊÅØËøõË°åÂà†Èô§Êìç‰Ωú\n>       deletePerInforAndComInfor()\n\ntest_flow\\test_Authentication\\test_personalInfoReg.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\dbLink.py:82: in deletePerInforAndComInfor\n    Sqldata(sqlStr5, 2)\ncommon\\dbLink.py:25: in Sqldata\n    cursor.execute(sqlStr)\n..\\venv\\lib\\site-packages\\pymysql\\cursors.py:163: in execute\n    result = self._query(query)\n..\\venv\\lib\\site-packages\\pymysql\\cursors.py:321: in _query\n    conn.query(q)\n..\\venv\\lib\\site-packages\\pymysql\\connections.py:505: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n..\\venv\\lib\\site-packages\\pymysql\\connections.py:724: in _read_query_result\n    result.read()\n..\\venv\\lib\\site-packages\\pymysql\\connections.py:1069: in read\n    first_packet = self.connection._read_packet()\n..\\venv\\lib\\site-packages\\pymysql\\connections.py:676: in _read_packet\n    packet.raise_for_error()\n..\\venv\\lib\\site-packages\\pymysql\\protocol.py:223: in raise_for_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b'\\xff\\xda\\x04#21000Subquery returns more than 1 row'\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        errval = data[9:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno)\n        if errorclass is None:\n            errorclass = InternalError if errno < 1000 else OperationalError\n>       raise errorclass(errno, errval)\nE       pymysql.err.OperationalError: (1242, 'Subquery returns more than 1 row')\n\n..\\venv\\lib\\site-packages\\pymysql\\err.py:107: OperationalError"}, "description": "ÊµãËØï http://10.10.128.152:10053/personal/set/certification ‰∏™‰∫∫ÂÆûÂêçËÆ§ËØÅ", "attachments": [{"name": "log", "source": "182e4bf1-e8a3-4325-b648-391b70ab7512-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "0bd7a856-5fc4-4e33-a5e5-e54fcbcf1b56-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "63f62814-98f9-40fa-b88e-bf2874edb019-attachment.txt", "type": "text/plain"}], "start": 1599525788360, "stop": 1599525788394, "uuid": "2c3c2bc4-b91e-4331-91b5-607bd6aec83b", "historyId": "28dda5313ff182aeade3becf47df4372", "testCaseId": "9cbf013f05cb6ad37536fb98be3bcb37", "fullName": "test_flow.test_Authentication.test_personalInfoReg#test_infoReg", "labels": [{"name": "severity", "value": "blocker"}, {"name": "tag", "value": "run(order=2)"}, {"name": "parentSuite", "value": "test_flow.test_Authentication"}, {"name": "suite", "value": "test_personalInfoReg"}, {"name": "host", "value": "A02-03-00033"}, {"name": "thread", "value": "28768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_flow.test_Authentication.test_personalInfoReg"}], "links": [{"type": "test_case", "url": "http://10.10.128.152:10053/personal/set/certification", "name": "‰∏™‰∫∫ÂÆûÂêçËÆ§ËØÅ üëá"}]}